In [59]:
import numpy as np

#input, mulai:1, selesai:28
a=int(input("Mulai:"))
b=int(input("Selesai:"))
one_dimension = np.arange(a, b)
#1 dimensi
print(one_dimension)
#2 dimensi
print(np.reshape(one_dimension, (3, 9)))
#3 dimensi
print(np.reshape(one_dimension, (3, 3,3)))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [69]:
#input banyak data :16, Mulai:1, Selesai:50
import numpy as np
n=int(input("Banyak Data:"))
m=int(input("Mulai:"))
s=int(input("Selesai:"))

one_dim = np.random.randint(m, s, n)
print(one_dim)

#2 dimensi
two_dim = np.reshape(one_dim, (4, 4))
print(two_dim)

#2 dimensi
#two_dim_sort = np.flip(two_dim,1)
two_dim_sort = two_dim[:,::-1]
print(two_dim_sort)



[43 21 25 24  5 14 15 15 31  9 28  3  6 35 44 36]
[[43 21 25 24]
 [ 5 14 15 15]
 [31  9 28  3]
 [ 6 35 44 36]]
[[24 25 21 43]
 [15 15 14  5]
 [ 3 28  9 31]
 [36 44 35  6]]
